(display "Ingrese el numero de manzanas del primer agricultor" )
(define agricultor_1 (read))
(newline)
(display "Ingrese el numero de manzanas del segundo agricultor" )
(define agricultor_2 (read))
(newline)
(display "ingrese el numero de manzanas del tercer agricultor" )
(define agricultor_3 (read))
(define manzanas_totales (+ agricultor_1 agricultor_2 agricultor_3))
(newline)
(define manzanas_hoy (quotient manzanas_totales 3 ))
(newline)
(define manzamas_mañana (remainder manzanas_totales 3))
(display manzanas_hoy)
