            (clear)
            (display "****  Ciencias de la Computacion - 2015 *****\n")
            (display "****  Laboratorio #5 - Ejercicio #1  *****\n\n")
            (display "Ingrese su nombre: ")
            (define nombre (read-line))
            (display "Ingrese su apellido: ")
            (define apellido (read-line))
            (display "Ingrese su edad: ")
            (define edad (read))
            (define x (string-length nombre))
            (define y (string-length apellido))
            (define respuesta (* (+ (random (+ edad 2))(random (+ edad 10))) (+ x y)))
            (display (string-append "Felicitaciones " nombre "!!!\n"))
            (display "Ejecutaste tu primer programa en Scheme :) !")
            (newline)
            (display "Su respuesta para este programa es: ")
            (display (number->string respuesta))
